name: viswa first CI/CD
on:
   push:
   schedule:
      - cron: *****
   workflow_dispatch:
   inputs:
      environment: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: viswa-checkout
        runs: echo 'This is testing'
        
       
