name: viswa first CI/CD
on:
   push
env:
  print_test: Viswa is working on the Github Action
jobs:
  call-template-job:
    uses: ./.github/workflows/reuse-template.yml
  sample-job:
    runs-on: ubuntu-latest
    needs: call-template-job
    steps:
      - run: echo "${{ env.print_test }}"
      - run: echo "${{ env.print_test }}"

  

        
       
